# For more information: https://laravel.com/docs/sail
version: '3'

services:
    laravel:
        image: tangramor/nginx-php8-fpm:php8.1.10_node18.8.0
        environment:
            WEBROOT: '/var/www/html/public'
            CREATE_LARAVEL_STORAGE: '1'
            COMPOSERMIRROR: 'https://mirrors.cloud.tencent.com/composer/'
            NPMMIRROR: 'https://registry.npmmirror.com'
        ports:
            - '${APP_PORT:-80}:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

networks:
    sail:
        driver: bridge
